export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as Contributions } from './Contributions'
export { default as Experience } from './Experience'
export { default as Projects } from './Projects'
export { default as Footer } from './Footer'
